- name: create tallessa service directory
  file: path={{ item }} state=directory owner=tallessadmin group=tallessa mode=02750
  with_items:
    - /srv/tallessa
    - /srv/tallessa/backend

- name: check out tallessa code from github
  become: yes
  become_user: tallessadmin
  git: >
    repo=https://github.com/tallessa/tallessa-backend.git
    dest=/srv/tallessa/backend/app
    version=master
  notify: restart tallessa
  tags:
    - deploy
    - deploy-tallessa-backend

- name: create tallessa virtualenv
  become: yes
  become_user: tallessadmin
  command: /usr/bin/env python3 -m venv /srv/tallessa/backend/virtualenv
  args:
    creates: /srv/tallessa/backend/virtualenv

- name: install tallessa dependencies
  pip: >
    requirements=/srv/tallessa/backend/app/requirements.txt
    virtualenv=/srv/tallessa/backend/virtualenv
  tags:
    - deploy
    - deploy-tallessa-backend

- name: create tallessa-backend .env file
  template: src=env.j2 dest=/srv/tallessa/backend/app/.env owner=tallessadmin group=tallessa mode=0640
  notify: restart tallessa
  tags:
    - deploy
    - deploy-tallessa-backend

- name: run python manage.py collectstatic for tallessa-backend
  become: yes
  become_user: tallessadmin
  command: /srv/tallessa/backend/virtualenv/bin/python manage.py collectstatic --noinput
  args:
    chdir: /srv/tallessa/backend/app
  tags:
    - deploy
    - deploy-tallessa-backend

- name: run python manage.py setup for tallessa-backend
  become: yes
  become_user: tallessa
  command: /srv/tallessa/backend/virtualenv/bin/python manage.py setup
  args:
    chdir: /srv/tallessa/backend/app
  tags:
    - deploy
    - deploy-tallessa-backend

- name: install tmpfiles.d configuration for tallessa
  copy: src=tallessa.tmpfiles.conf dest=/etc/tmpfiles.d/tallessa.conf

- name: install tallessa systemd files
  copy: src={{ item }} dest=/etc/systemd/system/{{ item }}
  with_items:
    - tallessa.service
    - tallessa.socket
  notify: restart tallessa

