---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: install basic packages
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - acl
    - build-essential
    - git
    - htop
    - python3-dev
    - python3-venv
    - screen
    - vim
    - wget
